format = "v1"
[[distfiles]]
name = "bianbu-24.04-desktop-k1-v2.1-release-20250124144655.img.zip"
size = 2615616404
urls = [ "https://archive.spacemit.com/image/k1/version/bianbu/v2.1/bianbu-24.04-desktop-k1-v2.1-release-20250124144655.img.zip",]
restrict = [ "mirror",]

[distfiles.checksums]
sha256 = "7e0ead6b6cc06beb086222d2e5f8a0522b4966ab80edb3f9318ed2fb19fbfc9c"
sha512 = "9a25792e6e768f339ad6b5c7237feca1e5b530ee8e27351d0860400dfed4d08972bfa3cd8796e2fa0860bcf6c36cee64cd89cec9a380bf50303dae821cb31a7f"

[metadata]
desc = "Official bianbu desktop image for Banana Pi F3 version v2.1"
service_level = []

[blob]
distfiles = [ "bianbu-24.04-desktop-k1-v2.1-release-20250124144655.img.zip",]

[provisionable]
strategy = "dd_v1"

[metadata.vendor]
name = "bpi_f3"
eula = ""

[provisionable.partition_map]
disk = "bianbu-24.04-desktop-k1-v2.1-release-20250124144655.img"

# This file is created by program Sync Package Index inside support-matrix
# Run ID: 13716811033
# Run URL: https://github.com/wychlw/support-matrix/actions/runs/13716811033
